name: Update Calendar

on:
  schedule:
    - cron: '0 0 * * 0' # 每周日午夜运行一次
  workflow_dispatch: # 允许手动触发

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4 icalendar

    - name: Run scraper
# 运行脚本生成新的 .ics 文件
      run: python scraper.py

    - name: Commit and push changes
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add catholic_hk_2026.ics
        git commit -m "Update calendar: $(date +'%Y-%m-%d')" || exit 0
        git push
